version: '2'
services:
  neurosynth:
    build: .
    restart: always
    ports:
      - "8000"
    volumes:
      - .:/code
      - ${ROOT}/data:/data
      - ${ROOT}/logs:/logs
    command: /code/scripts/docker_startup.sh
    depends_on:
      - db
      - redis

  db:
    restart: always
    image: postgres:10.4
    expose:
      - '5432'
    volumes:
      - ${ROOT}/postgres:/var/lib/postgresql/data

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    volumes_from:
      - neurosynth
    depends_on:
      - neurosynth

  redis:
    restart: always
    image: redis

  worker:
    image: nsweb_neurosynth:latest
    restart: always
    command: celery worker --app=nsweb.core:celery -c 1 --workdir=/code --logfile=/logs/celery/dev.log
    volumes_from:
      - neurosynth
    depends_on:
      - db
      - redis
